version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: deepseek-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-deepseek}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Web UI Application
  web-ui:
    build: ./web-ui
    container_name: deepseek-web-ui
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-deepseek}
      POSTGRES_HOST: postgres
      OLLAMA_HOST: ollama
      MODEL_NAME: ${MODEL_NAME:-deepseek-coder:6.7b-instruct-q5_K_M}
      SESSION_SECRET: ${SESSION_SECRET:-changeme_in_production}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    build: ./nginx
    container_name: deepseek-nginx
    depends_on:
      - web-ui
    ports:
      - "${PORT:-80}:80"
    environment:
      MAX_BODY_SIZE: ${MAX_BODY_SIZE:-10M}
      RATE_LIMIT_REQS: ${RATE_LIMIT_REQS:-10}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60s}
      FAILED_LOGIN_LIMIT: ${FAILED_LOGIN_LIMIT:-5}
      WEB_UI_HOST: web-ui
    volumes:
      - ./nginx/static:/usr/share/nginx/html/static
    restart: unless-stopped

  # Ollama Model Server
  ollama:
    image: ollama/ollama:latest
    container_name: deepseek-ollama
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres_data:
  ollama_data: