# File: docker-compose.yml
# Directory: /deepseek-coder-setup/

version: '3.8'

services:
  # PostgreSQL database for auth and chat history
  postgres:
    build:
      context: ./db
    container_name: deepseek-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - deepseek_network
    restart: unless-stopped

  # Ollama service for DeepSeek-Coder model
  ollama:
    image: ollama/ollama:latest
    container_name: deepseek-ollama
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"
    networks:
      - deepseek_network
    restart: unless-stopped

  # Quart-based Web UI
  web-ui:
    build:
      context: ./web-ui
    container_name: deepseek-web-ui
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      MODEL_NAME: ${MODEL_NAME:-deepseek-coder:6.7b-instruct-q5_K_M}
      OLLAMA_HOST: ollama
      SESSION_SECRET: ${SESSION_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    networks:
      - deepseek_network
    restart: unless-stopped

  # NGINX for authentication, rate limiting and GZIP compression
  nginx:
    build:
      context: ./nginx
    container_name: deepseek-nginx
    depends_on:
      - web-ui
    ports:
      - "${PORT:-8080}:80"
    environment:
      WEB_UI_HOST: web-ui
      MAX_BODY_SIZE: ${MAX_BODY_SIZE:-10M}
      RATE_LIMIT_REQS: ${RATE_LIMIT_REQS:-10}
      RATE_LIMIT_WINDOW: ${RATE_LIMIT_WINDOW:-60s}
      FAILED_LOGIN_LIMIT: ${FAILED_LOGIN_LIMIT:-5}
    networks:
      - deepseek_network
    restart: unless-stopped

networks:
  deepseek_network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data: